name: nethack
version: 3.4.2-2
summary: The popular nethack console adventure
description: Play the nethack cli version
confinement: strict

apps:
    nethack:
      command: ./nethack.sh
      plugs: [home]

parts:
  nethack:
    source: ./
    plugin: make
    build-packages:
      - bison
      - bsdmainutils
      - flex
      - gcc-5
      - groff-base
      - gzip
      - libncurses5-dev
      - patch
      - sharutils
      - tar
      - wget
    stage-packages:
      - libncurses5
      - libc-bin
      - console-setup-linux
      - locales
