name: nethack
version: 3.6.1-0
summary: The popular nethack console adventure
description: Play the nethack cli version
confinement: strict
grade: stable

apps:
    nethack:
      command: ./nethack.sh
      plugs: [home]

parts:
  nethack:
    source: https://github.com/NetHack/NetHack.git
    source-branch: NetHack-3.6.0
    plugin: make
    override-build: |
      cd sys/unix
      sed -i 's/^PREFIX=.*/PREFIX=$(SNAPCRAFT_PART_INSTALL)/' hints/linux
      sed -i 's/^CFLAGS+=-DSYSCF.*//' hints/linux
      ./setup.sh hints/linux
      cd ../../
      snapcraftctl build
      cp ../../../nethack.sh $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - bison
      - bsdmainutils
      - flex
      - gcc
      - groff-base
      - gzip
      - libncurses5-dev
      - patch
      - sharutils
      - tar
      - wget
    stage-packages:
      - libncurses5
      - libc-bin
      - console-setup-linux
      - locales
